// Generated by scripts/build-card-scenes.ts — do not edit by hand.
export const CARD_SCENES: Record<string, number> = {
  'acinonyx jubatus': require('../../../assets/cards/species/acinonyx-jubatus.webp'),
  'ailurus fulgens': require('../../../assets/cards/species/ailurus-fulgens.webp'),
  'alcedo atthis': require('../../../assets/cards/species/alcedo-atthis.webp'),
  'ardea cinerea': require('../../../assets/cards/species/ardea-cinerea.webp'),
  'carcharodon carcharias': require('../../../assets/cards/species/carcharodon-carcharias.webp'),
  'columba livia': require('../../../assets/cards/species/columba-livia.webp'),
  'felis catus': require('../../../assets/cards/species/felis-catus.webp'),
  'parus major': require('../../../assets/cards/species/parus-major.webp'),
  'vulpes vulpes': require('../../../assets/cards/species/vulpes-vulpes.webp'),
};
