import catalog from '../convex/data/catalog.json';

declare const Bun: {
  file: (path: string) => { exists: () => Promise<boolean> };
  write: (path: string, data: string) => Promise<number>;
};

const assetDir = 'assets/cards/species';
const output = 'src/components/cards/card-scenes.generated.ts';

export function speciesKey(name: string) {
  return name.trim().toLowerCase().split(/\s+/).slice(0, 2).join(' ');
}

export function speciesSlug(name: string) {
  return speciesKey(name).replace(/[^a-z0-9]+/g, '-');
}

const candidates = (await Promise.all(catalog.species.map(async (species) => {
  const key = speciesKey(species.canonicalName);
  const slug = speciesSlug(species.canonicalName);
  return { exists: await Bun.file(`${assetDir}/${slug}.webp`).exists(), key, slug };
})))
  .filter(({ exists }) => exists);
const rows = [...new Map(candidates.map((row) => [row.key, row])).values()]
  .sort((a, b) => a.key.localeCompare(b.key));

const source = `// Generated by scripts/build-card-scenes.ts — do not edit by hand.\n` +
  `export const CARD_SCENES: Record<string, number> = {\n` +
  rows.map(({ key, slug }) => `  '${key}': require('../../../assets/cards/species/${slug}.webp'),`).join('\n') +
  `\n};\n`;

await Bun.write(output, source);
console.log(`card-scenes: ${rows.length}/${catalog.species.length}`);
